version: 1.0.{build}

branches:
    only:
        - master

          # init:
install: 
  - cinst autohotkey.install
#  - cinst onenote

  # Build.bat will include logic for running test program.
  # Will fail if test fails.
build_script:
    - cmd: build.bat


test: off
